### ISSUE TITLE
Could not reconnect anymore (probably driver issue)

### ISSUE THREAD

**Issue by matthid** [matthid/ilamp-communication#1]
```
Jun 15 22:24:42: DisconnectProfile '/org/bluez/hci0/dev_C9_A3_05_FE_BD_41' failed: System.AggregateException: One or more errors occurred. (org.bluez.Error.Failed: Operation already in progress) ---> Tmds.DBus.DBusException: org.bluez.Error.Failed: Operation already in progress
Jun 15 22:24:42:    at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
Jun 15 22:24:42:    at Tmds.DBus.Connection.CallMethodAsync(Message message)
Jun 15 22:24:42:    at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
Jun 15 22:24:42:    --- End of inner exception stack trace ---
Jun 15 22:24:42: ---> (Inner Exception #0) Tmds.DBus.DBusException: org.bluez.Error.Failed: Operation already in progress
Jun 15 22:24:42:    at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
Jun 15 22:24:42:    at Tmds.DBus.Connection.CallMethodAsync(Message message)
Jun 15 22:24:42:    at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)<---
Jun 15 22:24:42: Starting RFCOMM ... /org/bluez/hci0/dev_C9_A3_05_FE_BD_41
Jun 15 22:24:42: Fatal: Reading task failed - System.Exception: UnixIOException in read task ---> Mono.Unix.UnixIOException: Software caused connection abort [ECONNABORTED].
Jun 15 22:24:42:    at Mono.Unix.UnixMarshal.ThrowExceptionForLastError()
Jun 15 22:24:42:    at Mono.Unix.UnixStream.Read(Byte[] buffer, Int32 offset, Int32 count)
Jun 15 22:24:42:    at System.IO.Stream.<>c.<BeginReadInternal>b__40_0(Object <p0>)
Jun 15 22:24:42:    at System.Threading.Tasks.Task`1.InnerInvoke()
Jun 15 22:24:42:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Jun 15 22:24:42: --- End of stack trace from previous location where exception was thrown ---
Jun 15 22:24:42:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
Jun 15 22:24:42:    --- End of inner exception stack trace ---
Jun 15 22:24:42:    at Server.handleErr@300-1.Invoke(Unit unitVar) in E:\Projects\ilamp-communication\src\ilamp-communication\Server.fs:line 311
Jun 15 22:24:42:    at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
Jun 15 22:24:42:    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
Jun 15 22:24:42: reading task crashed: System.Exception: UnixIOException in read task ---> Mono.Unix.UnixIOException: Software caused connection abort [ECONNABORTED].
Jun 15 22:24:42:    at Mono.Unix.UnixMarshal.ThrowExceptionForLastError()
Jun 15 22:24:42:    at Mono.Unix.UnixStream.Read(Byte[] buffer, Int32 offset, Int32 count)
Jun 15 22:24:42:    at System.IO.Stream.<>c.<BeginReadInternal>b__40_0(Object <p0>)
Jun 15 22:24:42:    at System.Threading.Tasks.Task`1.InnerInvoke()
Jun 15 22:24:42:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Jun 15 22:24:42: --- End of stack trace from previous location where exception was thrown ---
Jun 15 22:24:42:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
Jun 15 22:24:42:    --- End of inner exception stack trace ---
Jun 15 22:24:42:    at Server.handleErr@300-1.Invoke(Unit unitVar) in E:\Projects\ilamp-communication\src\ilamp-communication\Server.fs:line 311
Jun 15 22:24:42:    at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
Jun 15 22:24:42:    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
Jun 15 22:24:44: Warning: RFCOMM connection stopped with 'ENOTCONN' (lamp might be turned off), reconnecting... - Mono.Unix.UnixIOException: Transport endpoint is not connected [ENOTCONN].
Jun 15 22:24:44:    at Mono.Unix.UnixMarshal.ThrowExceptionForLastError()
Jun 15 22:24:44:    at Mono.Unix.UnixStream.Write(Byte[] buffer, Int32 offset, Int32 count)
Jun 15 22:24:44:    at System.IO.Stream.<>c.<BeginWriteInternal>b__49_0(Object <p0>)
Jun 15 22:24:44:    at System.Threading.Tasks.Task`1.InnerInvoke()
Jun 15 22:24:44:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Jun 15 22:24:44: --- End of stack trace from previous location where exception was thrown ---
Jun 15 22:24:44:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
Jun 15 22:24:44: Starting RFCOMM ... /org/bluez/hci0/dev_C9_A3_05_FE_BD_41
Jun 15 22:24:44: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Jun 15 22:24:44:       Request finished in 23.2874ms 200 application/json; charset=utf-8
Jun 15 22:24:44: Connection attempt failed, trying again in 5 seconds: System.AggregateException: One or more errors occurred. (org.bluez.Error.InProgress: In Progress) ---> Tmds.DBus.DBusException: org.bluez.Error.InProgress: In Progress
Jun 15 22:24:44:    at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
Jun 15 22:24:44:    at Tmds.DBus.Connection.CallMethodAsync(Message message)
Jun 15 22:24:44:    at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
Jun 15 22:24:44:    --- End of inner exception stack trace ---
Jun 15 22:24:44: ---> (Inner Exception #0) Tmds.DBus.DBusException: org.bluez.Error.InProgress: In Progress
Jun 15 22:24:44:    at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
Jun 15 22:24:44:    at Tmds.DBus.Connection.CallMethodAsync(Message message)
Jun 15 22:24:44:    at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)<---
Jun 15 22:24:49: Starting RFCOMM ... /org/bluez/hci0/dev_C9_A3_05_FE_BD_41
```

**Comment by matthid** [comment]
Workaround: Delete Bluetooth device and restart bluetooth
